### ISSUE TITLE
Support for running this from a web page

### ISSUE THREAD

**Issue by redneb** [ide/await-lock#6]
Is this module intended to be used on the web platform, or is it node only? By glancing through the code, it appears that the only node specific bit is the call to `assert`. Would you consider removing it for the benefit of making it possible to use this on the web?

**Comment by ide** [comment]
Since lots of libraries use assert, I’d expect your run into a similar issue with another library even if the assert call here were replaced with a plain exception. Webpack and Browserify can polyfill the assert module — have you looked into that for your use case?

**Comment by redneb** [comment]
I use `rollup` as my bundler and it doesn't handle `assert` automatically. There is also a [package on npm](https://www.npmjs.com/package/assert) that provides a polyfill for `assert` but it has a lot of dependencies (relative to the size `await-lock`) and I don't want to use it because of that.

**Comment by ide** [comment]
https://github.com/ide/await-lock/releases/tag/v2.0.1
